### ISSUE TITLE
Custom events not working

### ISSUE THREAD

**Issue by nittolese** [uschmidt83/plausible-events#1]
Hi,
thanks for this amazing lib!
I'm trying to trigger custom events from the server side without luck.

If I run JS events on the frontend, it works (following [official docs](https://plausible.io/docs/custom-event-goals#want-to-trigger-custom-events-manually-with-custom-javascript) )
```
window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }
plausible('TEST')
```

But on my python code, it seems that events are not sent:

```
from plausible_events import PlausibleEvents
pe = PlausibleEvents(domain="<my-domain>")
pe.event("SSE-TEST")
```

What I'm doing wrong?
Thanks!

**Comment by uschmidt83** [comment]
Hi @nittolese and sorry for the late reply.

I don't think you're doing anything wrong. Can you try running it with debug messages enabled?

For example, this code
```python
from plausible_events import PlausibleEvents

# create object to record events for your plausible.io domain
pe = PlausibleEvents(domain='test.stardist.net', debug=True)

# record a page view event with a (hypothetical) path
pe.pageview('/login/user')

# record a custom event with additional custom properties
pe.event('my event', dict(os='mac', var='foo'))
```

generates these debug messages:

```
main:   append task
main:   start worker
worker: run task
main:   append task
main:   append task
worker: run task
event:  name='pageview', path='login/user', headers=None, utm=None, props={}
worker: run task
event:  name='my event', path='', headers=None, utm=None, props={'os': 'mac', 'var': 'foo'}
```

**Comment by nittolese** [comment]
Hi @uschmidt83 , sorry for the late reply!

I got this output:

```
main:   append task
main:   start worker
worker: run task
main:   append task
main:   append task

worker: run task
event:  name='pageview', path='login/user', headers=None, utm=None, props={}
worker: run task
event:  name='my event', path='', headers=None, utm=None, props={'os': 'mac', 'var': 'foo'}
```

Still nothing in my dashboard, it's really strange

**Comment by uschmidt83** [comment]
> Still nothing in my dashboard, it's really strange

Ok, so you ran my code as is, but only changed `domain`?

What do you mean by "nothing in my dashboard"? No page view event at all? If the goal `my event` isn't showing up under "Goal conversions", you need to add it first under `Site settings > Goals > Add goal` as a "Custom event".

**Comment by nittolese** [comment]
@uschmidt83 I've added the Goal to my Plausible dashboard but still nothing. I've sent you an email with my screen recording.

**Comment by uschmidt83** [comment]
@nittolese did you ever resolve the issue after I replied to your email?

**Comment by nittolese** [comment]
@uschmidt83 yup! The issue was to use the domain you want to track instead of the subdomain where Plausible is installed.
Thank you!
